services:
  - type: web
    name: rent-car
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    autoDeploy: true
